# Generated by Django 5.1.3 on 2024-12-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chariot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nb_lingots', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Chariot',
            },
        ),
        migrations.CreateModel(
            name='EntreeStock',
            fields=[
                ('idEntreeStock', models.AutoField(primary_key=True, serialize=False)),
                ('DateEntreST', models.DateField(null=True)),
                ('Magasinier', models.CharField(max_length=100, null=True)),
                ('nb', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('idFournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=255, null=True)),
                ('Adresse', models.CharField(max_length=255, null=True)),
                ('Tel', models.CharField(max_length=15, null=True)),
                ('PaysOrigine', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneSerti',
            fields=[
                ('idLigneSerti', models.AutoField(primary_key=True, serialize=False)),
                ('Typeligne', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitFini',
            fields=[
                ('idProduitFini', models.AutoField(primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=255, null=True)),
                ('Description', models.TextField(null=True)),
                ('Format', models.CharField(max_length=50, null=True)),
                ('Milieux', models.CharField(max_length=50, null=True)),
                ('Type_2', models.CharField(max_length=50, null=True)),
                ('Miette', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consom', models.DateField(blank=True, null=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hdebut', models.DateTimeField(blank=True, null=True)),
                ('hfin', models.DateTimeField(blank=True, null=True)),
                ('chariot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.chariot')),
                ('ligne_serti', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.ligneserti')),
            ],
            options={
                'db_table': 'Consommation',
            },
        ),
        migrations.CreateModel(
            name='MatiereP',
            fields=[
                ('IdMP', models.AutoField(primary_key=True, serialize=False)),
                ('Lot', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('DateFabrication', models.DateField(null=True)),
                ('DatePeremption', models.DateField(null=True)),
                ('Reste', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='EntreeSTMP',
            fields=[
                ('idEntreeSTMP', models.AutoField(primary_key=True, serialize=False)),
                ('QuantitEntree', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('EntreeStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.entreestock')),
                ('MatiereP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.matierep')),
            ],
        ),
        migrations.CreateModel(
            name='PaletteMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbcolis', models.IntegerField(blank=True, null=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('matiere_p', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.matierep')),
            ],
            options={
                'db_table': 'PaletteMP',
            },
        ),
        migrations.AddField(
            model_name='chariot',
            name='palette_mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.palettemp'),
        ),
        migrations.CreateModel(
            name='ProductionLigne',
            fields=[
                ('idProductionLigne', models.AutoField(primary_key=True, serialize=False)),
                ('DateProd', models.DateField(null=True)),
                ('HDebut', models.DateTimeField(null=True)),
                ('HFin', models.DateTimeField(null=True)),
                ('quantitePL', models.PositiveIntegerField(null=True)),
                ('Lot', models.PositiveIntegerField(null=True)),
                ('LotF', models.CharField(max_length=50, null=True)),
                ('LotM', models.CharField(max_length=50, null=True)),
                ('CompteurBrut', models.PositiveIntegerField(null=True)),
                ('Avarie', models.PositiveIntegerField(null=True)),
                ('CompteurNet', models.PositiveIntegerField(null=True)),
                ('MoyennePoidsNet', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('MoyennePoidsemb1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('MoyennePoidEmb2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('MPS_Eau', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('LigneSerti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ligneserti')),
                ('ProduitFini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.produitfini')),
            ],
        ),
        migrations.CreateModel(
            name='SortieSTTMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie_st', models.DateField(blank=True, null=True)),
                ('quantite_sortie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('matiere_p', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.matierep')),
            ],
            options={
                'db_table': 'SortieSTTMP',
            },
        ),
    ]
