# Generated by Django 5.1.3 on 2024-12-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entreestmp',
            table='EntreeSTMP',
        ),
        migrations.AlterModelTable(
            name='entreestock',
            table='EntreeStock',
        ),
        migrations.AlterModelTable(
            name='fournisseur',
            table='Fournisseur',
        ),
        migrations.AlterModelTable(
            name='ligneserti',
            table='LigneSerti',
        ),
        migrations.AlterModelTable(
            name='matierep',
            table='MatiereP',
        ),
        migrations.AlterModelTable(
            name='productionligne',
            table='ProductionLigne',
        ),
        migrations.AlterModelTable(
            name='produitfini',
            table='ProduitFini',
        ),
    ]
